keep exit code of 1 even with tee

diff --git a/.github/workflows/autoupdate.yml b/.github/workflows/autoupdate.yml
--- a/.github/workflows/autoupdate.yml
+++ b/.github/workflows/autoupdate.yml
@@ -92,7 +92,11 @@ jobs:
             echo "Running autoupdate command..."
             cd "$REPO"
             # This may fail
+            # To get an exit code of 1 even with tee:
+            set -o pipefail
             planemo autoupdate . --skiplist "${{ github.workspace }}/autoupdate/${{ matrix.upstream_repo_owner }}_${{ matrix.upstream_repo_name }}_skip_list" 2>&1 1> "${{ github.workspace }}/autoupdate.log" | tee "${{ github.workspace }}/autoupdate.err" || errors="${errors}\nCannot autoupdate $REPO, last line of stderr is\n$(tail -n 1 "${{ github.workspace }}/autoupdate.err")"
+            # Restore
+            set +o pipefail
             # Waiting for https://github.com/galaxyproject/planemo/issues/1478 to be solved
             if [[ "$(tail -n 1 "${{ github.workspace }}/autoupdate.log")" = "Could not update"* ]]; then
               errors="${errors}\n$(tail -n 1 "${{ github.workspace }}/autoupdate.log")\n$(tail -n 1 "${{ github.workspace }}/autoupdate.err")"
